# Generated by Django 4.1.6 on 2023-03-20 06:21

from django.db import migrations, models
import snippets.models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='code_screen',
            field=models.ImageField(blank=True, null=True, upload_to=snippets.models.upload_to),
        ),
    ]
